server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///yeb?serverTimezone=UTC&characterEncodeing=UTF-8
    username: root
    password: 123456
    hikari:
      # 连接池名字
      pool-name: DataHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认60000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0 表示永久，默认1800000（30分钟）
      max-lifetime: 1800000
      # 测试连接是否可用的查询语句
      connection-test-query: select 1
  redis:
    timeout: 10000ms
    host: 47.106.71.32
    port: 6379
    database: 0
    # password:
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 1024
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空先连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5


mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.coolrui.server.pojo
  configuration:
    map-underscore-to-camel-case: false  # 自动驼峰命名

# MyBatis SQL打印(方法接口所在的包。不是Mapper.xml所在的包)
logging:
  level:
    com.coolrui.server.mapper: debug


jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT 过期时间  7天
  expiration: 60480
  # JWT 负载中拿到的开头
  tokenHead: Bearer
